 version: 2
 build:
   os: "ubuntu-24.04"
   tools:
     nodejs: "23"
   jobs:
     # "docs/" was created following the Docusaurus tutorial:
     # npx create-docusaurus@latest docs classic
     # but you can just use your existing Docusaurus site
     install:
       # Install Docusaurus dependencies
       - cd docs/ && npm install
     build:
       html:
         # Build the site
         - cd docs/ && npm run build
         # Copy generated files into Read the Docs directory
         - mkdir --parents $READTHEDOCS_OUTPUT/html/
         - cp --recursive docs/build/* $READTHEDOCS_OUTPUT/html/
