import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)


const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Documentation',
      items: [
        { type: 'autogenerated', dirName: '.' },
      ],
    },

    // --- Manual external links ---
    {
      type: 'link',
      label: 'Ask a question',
      href: 'https://github.com/pgscatalog/pgsc_calc/discussions',
    },
    {
      type: 'link',
      label: 'Report a problem',
      href: 'https://github.com/pgscatalog/pgsc_calc/issues',
    },
    {
      type: 'link',
      label: 'Changelog',
      href: 'https://github.com/pgscatalog/pgsc_calc/releases/',
    },
    {
      type: 'link',
      label: 'PGS training 🪄',
      href: 'https://www.ebi.ac.uk/training/online/courses/polygenic-scores-pgs-catalog/',
    },
    {
      type: 'link',
      label: 'PGS Catalog',
      href: 'https://pgscatalog.org/',
    },
  ],
};

export default sidebars;
