name: Preload singularity containers

on:
  workflow_call:
    outputs:
      cache-key:
        value: singularity-${{ github.sha }}

env:
  NXF_SINGULARITY_CACHEDIR: ${{ github.workspace }}/singularity

jobs:
  singularity:
    runs-on: ubuntu-latest
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v4

      - name: Singularity install with defaults
        uses: singularityhub/install-singularity@main

      - name: Pull and save apptainer images
        run: |
          mkdir -p $NXF_SINGULARITY_CACHEDIR
          git grep 'ext.docker*' conf/modules.config | cut -f 2 -d '=' | xargs -L 2 echo | tr -d ' ' > ${{ runner.temp }}/singularity_images.txt
          cat ${{ runner.temp }}/singularity_images.txt | sed 's/oras:\/\///;s/https:\/\///;s/\//-/g;s/$/.img/;s/:/-/' > ${{ runner.temp }}/singularity_image_paths.txt
          paste -d '\n' ${{ runner.temp }}/singularity_image_paths.txt ${{ runner.temp }}/singularity_images.txt | xargs -L 2 sh -c 'singularity pull --disable-cache --dir $NXF_SINGULARITY_CACHEDIR $0 $1'

      - name: Cache singularity images
        id: cache-singularity-pull
        uses: actions/cache@v4
        with:
          path: ${{ env.NXF_SINGULARITY_CACHEDIR }}
          key: apptainer-${{ github.sha }}
