name: Run standard test with singularity and docker profiles

on:
  workflow_call:
    inputs:
      cache-key:
        type: string
        required: true
      docker:
        type: boolean
      singularity:
        type: boolean

env:
  NXF_SINGULARITY_CACHEDIR: ${{ github.workspace }}/singularity
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  docker:
    if: ${{ inputs.docker }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test_profile: ["test"]
        profile: ["docker"]
        nxf_ver: ['23.10.0', 'latest']

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - uses: nf-core/setup-nextflow@v2
        with:
          version: ${{ matrix.nxf_ver }}

      - name: Restore docker images
        id: restore-docker
        uses: actions/cache/restore@v4
        with:
          path: ${{ runner.temp }}/docker
          key: ${{ inputs.cache-key }}
          fail-on-cache-miss: true

      - name: Load docker images from cache
        run: |
          find $HOME -name '*.tar'
          find ${{ runner.temp }}/docker/ -name '*.tar' -exec sh -c 'docker load < {}' \;

      - name: Run pipeline with test data
        run: |
          nextflow run pgscatalog/pgsc_calc -r ${{ steps.extract_branch.outputs.branch }} -profile ${{ matrix.test_profile}},${{ matrix.profile }}

  singularity:
    if: ${{ inputs.singularity }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test_profile: ["test"]
        profile: ["singularity"]
        nxf_ver: ['23.10.0', 'latest']

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - uses: nf-core/setup-nextflow@v2
        with:
          version: ${{ matrix.nxf_ver }}


      - name: Singularity install with defaults
        uses: singularityhub/install-singularity@main

      - name: Restore singularity container images
        id: restore-singularity
        uses: actions/cache@v4
        with:
          path: ${{ env.NXF_SINGULARITY_CACHEDIR }}
          key: ${{ inputs.cache-key }}
          fail-on-cache-miss: true

      - name: Run pipeline with test data
        run: |
          nextflow run pgscatalog/pgsc_calc -r ${{ steps.extract_branch.outputs.branch }} -profile ${{ matrix.test_profile}},${{ matrix.profile }}
